---
- name: Install kea dhcp6
  ansible.builtin.apt:
    name: "{{ kea_dhcp6_package }}"
    state: present

- name: Configure kea dhcp6
  ansible.builtin.template:
    src: kea-dhcp6.conf
    dest: /etc/kea/kea-dhcp6.conf
  notify: restart isc-kea-dhcp6-server

- name: Start and enable kea dhcp6
  ansible.builtin.service:
         name: isc-kea-dhcp6-server
         state: started
          enabled: yes
